# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rails db:seed command (or created alongside the database with db:setup).
#
# Examples:
#
#   movies = Movie.create([{ name: 'Star Wars' }, { name: 'Lord of the Rings' }])
#   Character.create(name: 'Luke', movie: movies.first)

user = User.create!(username: 'steevwgrhet', email: 'efsg@egsrhdrb.com', password: 'afsdvey')

Item.create!(title: 'Power Rangers', description: 'Go Go Power Rangers! WEOSWWWEAHHWOOAWOAHWOAH', user: user)
Item.create!(title: 'Magic School Bus', description: 'Ms. Frizzle taught us science', user: user)
Item.create!(title: 'Fall of the Soviet Union', description: 'A victory for capitalism and the free world', user: user)
Item.create!(title: 'Power Rangers', description: 'Go Go Power Rangers! WEOSWWWEAHHWOOAWOAHWOAH', user: user)
Item.create!(title: 'Magic School Bus', description: 'Ms. Frizzle taught us science', user: user)
Item.create!(title: 'Fall of the Soviet Union', description: 'A victory for capitalism and the free world', user: user)
Item.create!(title: 'Power Rangers', description: 'Go Go Power Rangers! WEOSWWWEAHHWOOAWOAHWOAH', user: user)
Item.create!(title: 'Magic School Bus', description: 'Ms. Frizzle taught us science', user: user)
Item.create!(title: 'Fall of the Soviet Union', description: 'A victory for capitalism and the free world', user: user)
Item.create!(title: 'Power Rangers', description: 'Go Go Power Rangers! WEOSWWWEAHHWOOAWOAHWOAH', user: user)
Item.create!(title: 'Magic School Bus', description: 'Ms. Frizzle taught us science', user: user)
Item.create!(title: 'Fall of the Soviet Union', description: 'A victory for capitalism and the free world', user: user)
Item.create!(title: 'Power Rangers', description: 'Go Go Power Rangers! WEOSWWWEAHHWOOAWOAHWOAH', user: user)
Item.create!(title: 'Magic School Bus', description: 'Ms. Frizzle taught us science', user: user)
Item.create!(title: 'Fall of the Soviet Union', description: 'A victory for capitalism and the free world', user: user)
Item.create!(title: 'Power Rangers', description: 'Go Go Power Rangers! WEOSWWWEAHHWOOAWOAHWOAH', user: user)
Item.create!(title: 'Magic School Bus', description: 'Ms. Frizzle taught us science', user: user)
Item.create!(title: 'Fall of the Soviet Union', description: 'A victory for capitalism and the free world', user: user)
Item.create!(title: 'Power Rangers', description: 'Go Go Power Rangers! WEOSWWWEAHHWOOAWOAHWOAH', user: user)
Item.create!(title: 'Magic School Bus', description: 'Ms. Frizzle taught us science', user: user)
Item.create!(title: 'Fall of the Soviet Union', description: 'A victory for capitalism and the free world', user: user)
Item.create!(title: 'Power Rangers', description: 'Go Go Power Rangers! WEOSWWWEAHHWOOAWOAHWOAH', user: user)
Item.create!(title: 'Magic School Bus', description: 'Ms. Frizzle taught us science', user: user)
Item.create!(title: 'Fall of the Soviet Union', description: 'A victory for capitalism and the free world', user: user)
Item.create!(title: 'Power Rangers', description: 'Go Go Power Rangers! WEOSWWWEAHHWOOAWOAHWOAH', user: user)
Item.create!(title: 'Magic School Bus', description: 'Ms. Frizzle taught us science', user: user)
Item.create!(title: 'Fall of the Soviet Union', description: 'A victory for capitalism and the free world', user: user)
Item.create!(title: 'Power Rangers', description: 'Go Go Power Rangers! WEOSWWWEAHHWOOAWOAHWOAH', user: user)
Item.create!(title: 'Magic School Bus', description: 'Ms. Frizzle taught us science', user: user)
Item.create!(title: 'Fall of the Soviet Union', description: 'A victory for capitalism and the free world', user: user)
Item.create!(title: 'Power Rangers', description: 'Go Go Power Rangers! WEOSWWWEAHHWOOAWOAHWOAH', user: user)
Item.create!(title: 'Magic School Bus', description: 'Ms. Frizzle taught us science', user: user)
Item.create!(title: 'Fall of the Soviet Union', description: 'A victory for capitalism and the free world', user: user)
Item.create!(title: 'Power Rangers', description: 'Go Go Power Rangers! WEOSWWWEAHHWOOAWOAHWOAH', user: user)
Item.create!(title: 'Magic School Bus', description: 'Ms. Frizzle taught us science', user: user)
Item.create!(title: 'Fall of the Soviet Union', description: 'A victory for capitalism and the free world', user: user)
Item.create!(title: 'Power Rangers', description: 'Go Go Power Rangers! WEOSWWWEAHHWOOAWOAHWOAH', user: user)
Item.create!(title: 'Magic School Bus', description: 'Ms. Frizzle taught us science', user: user)
Item.create!(title: 'Fall of the Soviet Union', description: 'A victory for capitalism and the free world', user: user)
Item.create!(title: 'Power Rangers', description: 'Go Go Power Rangers! WEOSWWWEAHHWOOAWOAHWOAH', user: user)
Item.create!(title: 'Magic School Bus', description: 'Ms. Frizzle taught us science', user: user)
Item.create!(title: 'Fall of the Soviet Union', description: 'A victory for capitalism and the free world', user: user)
Item.create!(title: 'Power Rangers', description: 'Go Go Power Rangers! WEOSWWWEAHHWOOAWOAHWOAH', user: user)
Item.create!(title: 'Magic School Bus', description: 'Ms. Frizzle taught us science', user: user)
Item.create!(title: 'Fall of the Soviet Union', description: 'A victory for capitalism and the free world', user: user)
Item.create!(title: 'Power Rangers', description: 'Go Go Power Rangers! WEOSWWWEAHHWOOAWOAHWOAH', user: user)
Item.create!(title: 'Magic School Bus', description: 'Ms. Frizzle taught us science', user: user)
Item.create!(title: 'Fall of the Soviet Union', description: 'A victory for capitalism and the free world', user: user)
